version: '3.7'

services:
  greengrass:
    init: true
    build:
      context: .
      dockerfile: Dockerfile-greengrass
    container_name: etl-greengrass
    image: x86_64/greengrass-accelerator-etl:latest
    volumes:
      - ./certs:/greengrass/certs
      - ./config:/greengrass/config
      - ./deployment:/greengrass/ggc/deployment
      - ./log:/greengrass/ggc/var/log
      - ./redis:/etc/redis/db
    ports:
      - "8883:8883"
    entrypoint: "/greengrass-entrypoint.sh"